[package]
name = "xlsynth"
version = "0.0.4"
edition = "2018"
authors = ["Christopher D. Leary <cdleary@gmail.com>"]
description = "Accelerated Hardware Synthesis (XLS/XLSynth) via Rust"
license = "Apache-2.0"
repository = "https://github.com/xlsynth/xlsynth-crate"
documentation = "https://docs.rs/xlsynth"
homepage = "https://github.com/xlsynth/xlsynth-crate"

[dependencies]
libloading = "0.7"
libc = "0.2"
once_cell = "1.19"

[build-dependencies]
curl = "0.4"
