name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
      fail-fast: false

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Build crate
        run: cargo build -vv --lib

      - name: Test crate
        run: cargo test -vv --lib

      - name: Build workspace
        run: cargo build -vv --worksapce

      - name: Test workspace
        run: cargo test -vv --workspace
